#:schema node_modules/wrangler/config-schema.json
name = "rise-demo-http-server-inventory"
main = "src/index.tsx"
compatibility_date = "2024-04-29"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v1"
new_classes = ["InMemoryStorage"]
