#:schema node_modules/wrangler/config-schema.json
name = "rise-demo-http-server-inventory"
main = "src/index.ts"
compatibility_date = "2024-04-29"
compatibility_flags = ["nodejs_compat"]

durable_objects.bindings = [
  { name = "STORAGE", class_name = "InMemoryStorage" }
]
