name: Deploy Demo Server

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      project:
        description: Choose the project to deploy
        required: true
        default: demo
        type: choice
        options:
          - demo
          - demo-http

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "./example/${{ github.event.inputs.project }}"
